name: API Caller

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:        # allows manual run too

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call APIs
        run: |
          set -e  # stop on first error
          echo "Calling User Management API..."
          curl -f -X GET "https://user-management-api-oia5.onrender.com"
          
          echo "Calling S3 Connector API..."
          curl -f -X GET "https://s3-connector-backend.onrender.com"

